workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "iOS署名用"
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.privateprotect
      vars:
        XCODE_PROJECT: "ios_monitoring_app/PrivacyProtect.xcodeproj"
        XCODE_SCHEME: "PrivacyProtect"
        BUNDLE_ID: "com.privateprotect"
      xcode: latest
    scripts:
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create
      - name: Add certificates
        script: keychain add-certificates
      - name: Set signing settings
        script: xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcodebuild archive \
            -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -archivePath build/PrivacyProtect.xcarchive \
            -destination "generic/platform=iOS"
      - name: Export IPA
        script: |
          xcode-project build-ipa \
            --archive build/PrivacyProtect.xcarchive
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/*.xcarchive
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
