workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.privateprotect
      vars:
        XCODE_PROJECT: "ios_monitoring_app/PrivacyProtect.xcodeproj"
        XCODE_SCHEME: "PrivacyProtect"
        BUNDLE_ID: "com.privateprotect"
        APP_NAME: "Complete privacy protection"
      xcode: latest
    scripts:
      - name: Set up project
        script: |
          cd $CM_BUILD_DIR
          xcodebuild -project $XCODE_PROJECT -scheme $XCODE_SCHEME -showBuildSettings
      - name: Build iOS App
        script: |
          xcodebuild build \
            -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Build for Archive
        script: |
          xcodebuild archive \
            -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -archivePath build/PrivacyProtect.xcarchive \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/**/*.xcarchive
      - build/**/*.ipa
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
