workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: ios_monitoring_app
    integrations:
      app_store_connect: "iOS署名用"
    environment:
      groups:
        - signing
      vars:
        XCODE_PROJECT: "PrivacyProtect.xcodeproj"
        XCODE_SCHEME: "PrivacyProtect"
        BUNDLE_ID: "com.privateprotect"
      xcode: latest
    scripts:
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_DEVELOPMENT \
            --create
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Set up code signing settings
        script: xcode-project use-profiles
      - name: List available schemes
        script: |
          xcodebuild -project $XCODE_PROJECT -list || true
      - name: Build iOS App
        script: |
          xcodebuild -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/PrivacyProtect.xcarchive \
            -destination "generic/platform=iOS" \
            archive \
            DEVELOPMENT_TEAM="$APP_STORE_CONNECT_TEAM_ID" \
            CODE_SIGN_IDENTITY="Apple Development" \
            CODE_SIGN_STYLE=Automatic
      - name: Export IPA
        script: |
          cat > exportOptions.plist << PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>${APP_STORE_CONNECT_TEAM_ID}</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          PLIST
          
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/PrivacyProtect.xcarchive \
            -exportPath $CM_BUILD_DIR/build/ipa \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/ipa/*.ipa
      - build/*.xcarchive/**
