workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: ios_monitoring_app
    integrations:
      app_store_connect: "iOS署名用"
    environment:
      groups:
        - signing
      vars:
        XCODE_PROJECT: "PrivacyProtect.xcodeproj"
        XCODE_SCHEME: "PrivacyProtect"
        BUNDLE_ID: "com.privateprotect"
        TEAM_ID: "RZAA53F2U5"
      xcode: latest
    scripts:
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_DEVELOPMENT \
            --create
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Set up code signing settings
        script: xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcodebuild -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/PrivacyProtect.xcarchive \
            -destination "generic/platform=iOS" \
            archive
      - name: Export IPA
        script: |
          xcode-project build-ipa \
            --project $XCODE_PROJECT \
            --scheme $XCODE_SCHEME \
            --archive-directory $CM_BUILD_DIR/build
    artifacts:
      - build/ios/ipa/*.ipa
      - build/*.ipa
      - "**/*.ipa"
