workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "ios_monitoring_app/PrivacyProtect.xcodeproj"
        XCODE_SCHEME: "PrivacyProtect"
        BUNDLE_ID: "com.privateprotect"
        APP_NAME: "Complete privacy protection"
      xcode: latest
    scripts:
      - name: Build iOS App (Unsigned)
        script: |
          xcodebuild build \
            -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -sdk iphonesimulator \
            -destination "generic/platform=iOS Simulator" \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
