workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.privateprotect
      vars:
        XCODE_PROJECT: "ios_monitoring_app/PrivacyProtect.xcodeproj"
        XCODE_SCHEME: "PrivacyProtect"
        BUNDLE_ID: "com.privateprotect"
        APP_NAME: "Complete privacy protection"
      xcode: latest
    scripts:
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_ADHOC \
            --create
      - name: Use signing profiles
        script: keychain add-certificates
      - name: Set signing settings
        script: xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcodebuild build \
            -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/PrivacyProtect.xcarchive \
            archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/PrivacyProtect.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ~/export_options.plist
    artifacts:
      - build/ipa/*.ipa
      - build/**/*.xcarchive
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
